spring:
  application:
    name: vipa
  datasource:
    url: jdbc:postgresql://localhost:5432/vipa_db
    username: postgres
    password: admin
  flyway:
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
logging:
  level:
    org.thymeleaf: DEBUG

