spring:
  application:
    name: vipa
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
          must-revalidate: true
  servlet:
    multipart:
      location: ./uploads
      max-file-size: 50MB
  thymeleaf:
    extras:
      springsecurity6:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/vipa_db
    username: postgres
    password: admin
  flyway:
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: trifanya.onlinestore@gmail.com
    password: puxhjgrhvwhypkjl
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        debug: true

logging:
  level:
    org.thymeleaf: INFO

