spring:
  application:
    name: vipa
  datasource:
    url: jdbc:postgresql://localhost:5432/vipa-db
    username: postgres
    password: My_passw0rd
  flyway:
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true

