--INSERT INTO post
--(title,    price, status, number_of_views, client_id, category_id, description,    address,   created_at)
--VALUES
--('title1', 1000, 'status', 0,              1,         1,          'description1', 'address1', CURRENT_DATE),
--('title2', 100,  'status', 0,              2,         2,          'description2', 'address2', CURRENT_DATE),
--('title3', 5000, 'status', 0,              3,         3,          'description3', 'address3', CURRENT_DATE),
--('title4', 2500, 'status', 0,              4,         3,          'description4', 'address4', CURRENT_DATE),
--('title5', 250,  'status', 0,              5,         2,          'description5', 'address5', CURRENT_DATE),
--('title6', 700,  'status', 0,              1,         1,          'description6', 'address6', CURRENT_DATE),
--('title7', 1200, 'status', 0,              3,         2,          'description7', 'address7', CURRENT_DATE),
--('title8', 1450, 'status', 0,              5,         1,          'description8', 'address8', CURRENT_DATE),
--('title9', 150,  'status', 0,              5,         3,          'description9', 'address9', CURRENT_DATE)
--;